project_id = "cesohdhspysooaowtvsu"

[functions.generate-copy-ai]
verify_jwt = false

[functions.anthropic-copias]
verify_jwt = false

[functions.generate-analise-bench]
verify_jwt = false

[functions.generate-case-copy]
verify_jwt = false

[functions.test-anthropic]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.update-user-role]
verify_jwt = false

[functions.validate-handoff-token]
verify_jwt = false

[functions.apply-auto-tags]
verify_jwt = false

[functions.auto-move-cards]
verify_jwt = false

[functions.create-crm-lead]
verify_jwt = false

[functions.generate-csm-alerts]
verify_jwt = false

[functions.insert-success-case]
verify_jwt = false

[functions.news]
verify_jwt = false

[functions.generate-news-thumbnail]
verify_jwt = false
